### PR TITLE
currentToken can be null when calling queryEntities

### PR DESCRIPTION
**Pull request by ulrikaugustsson**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ulrikaugustsson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by hasonmsft** [comment]
@ulrikaugustsson , after testing this change, I found I'm getting compilation error with typescript@1.6.2

Here is the test ts file:
```
import azure = require('azure-storage');

var tableService = azure.createTableService();
var tableQuery = new azure.TableQuery();
tableService.queryEntities('test', tableQuery, null/*currentToken*/, function(err){

});
```

And the error is:
```
../node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(4544,117): error TS1110: Type expected.
../node_modules/azure-storage/typings/azure-storage/azure-storage.d.ts(4561,117): error TS1110: Type expected.
```

After reverting your change, the compilation passed with both 1.6.2 and 2.1.6. 

I'm going to revert your PR. Please let me know in case of any concern and can you provide more detail for your error so that we can help? 

Thanks for your contribution again!

**Comment by ulrikaugustsson** [comment]
@hasonmsft but you can't use this with strictNullChecks. At least I can't with the current version and then the type system is pretty much useless for me.

**Comment by hasonmsft** [comment]
@ulrikaugustsson ， we need to support TS 1.* and 2.*. strictNullChecks is newly introduced in 2.0 and the only fix is to change the type to [xxx] | null? But the problem is that [xxx] | null is not available in TS 1.*. 

Or do you know any other way to fix this issue which is also supported by TS 1.*?

**Pull request merged**
