### PR TITLE
fix(typings): Allow null for cont. token in query

### PR DESCRIPTION
**Pull request by nicojs**
Make `currentToken` in `queryEntities` nullable so it is compatible for with the `--strictNullChecks` option.

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
Hi @nicojs, 

Thanks for the contribution! We will evaluate the typescript version upgrade item in next **major** release iteration, as the change would break grammars of typescript@1.x which we are currently supporting. It will be kept temporarily.

Welcome any further suggestions!

**Comment by nicojs** [comment]
Thanks for your explanation. When will the next major release be? TypeScript 1.x is pretty old, i think most of the world is using 2.x by now.

**Comment by XiaoningLiu** [comment]
We are making plans for next several sprints, this item is already included, hold on : )

**Comment by tatsuya-takahashi** [comment]
Hi, @XiaoningLiu .
When will npm-repository be updated? 
latest2.8.0 seems not to include this fix.

**Comment by XiaoningLiu** [comment]
@tatsuya-takahashi It's a breaking change, need take in v3.0.0 . Sorry for the inconvenience.

**Comment by tatsuya-takahashi** [comment]
@XiaoningLiu 
Thank you for your prompt reply.
It's OK.

**Pull request closed without merging**
