### PR TITLE
Update uuid to version 3.0.0

### PR DESCRIPTION
**Pull request by marcbachmann**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@marcbachmann__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hasonmsft** [comment]
@marcbachmann , thanks for your contribution. We'll to more validation accordingly to see if there is any issue.

**Comment by marcbachmann** [comment]
I saw that you have a typings file that contains node-uuid. It also needs an update.

**Comment by hasonmsft** [comment]
@marcbachmann , it's useless anymore. We can safely remove it. @XiaoningLiu , please help remove it from our repo. Our type definition file doesn't depend on the uuid anymore.

**Pull request merged**
