### PR TITLE
Added support for xArchive

### PR DESCRIPTION
**Pull request by XiaoningLiu**

### CODE REVIEW

**Comment by jiacfan** [comment]
Note to add '.' in the end of comments for ARCHIVE_STATUS in constants.js. And others LGTM.

**Comment by XiaoningLiu** [comment]
@jiacfan Fixed the '.' mentioned. Thanks for the reviewing!

**Comment by XiaoningLiu** [comment]
Fixed

---
In reply to: [323631853](https://github.com/Azure/azure-storage-node/pull/347#issuecomment-323631853) [](ancestors = 323631853)

**Comment by XiaoningLiu** [comment]
@jiacfan Added another fixing commit into this PR, can you re-view this PR?

**Comment by jiacfan** [comment]
LGTM

**Pull request merged**
