### PR TITLE
Add CodeQL security scanning

### PR DESCRIPTION
**Pull request by jhutchings1**
Hi, I'm a PM on the GitHub security team. This repository is eligible to try the new [GitHub Advanced Security code scanning](https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning) beta.

Code scanning runs a static analysis tool called CodeQL which scans your code at build time to find any potential security issues. We've tuned the set of queries to be only the most severe, most precise issues. We'll show alerts in the security tab, and we'll show alerts for any net new vulnerabilities on pull requests as well. We've tried to make this super developer friendly, but we'd love your feedback as we work through the beta. 

If you're interested in trying it out, you can merge this pull request to set up the Actions workflow.

### CODE REVIEW

**Comment by jhutchings1** [comment]
This build is working in my fork. It did find one potential issue, but it looks minor. If you're good with this, then I think it's good to merge. Thanks!

**Comment by ljian3377** [comment]
Thanks for your contribution. But will it be better if we skip the beta and wait for the GA release?

**Comment by jhutchings1** [comment]
@ljian3377 Ultimately, that's up to you. The feature is a beta, but there's no risk to your code or existing CI processes. If you decide you don't like how it works, you can always just delete the workflow and it'll stop running. We'd be very happy to have you testing it though!

**Comment by ljian3377** [comment]
We decided to skip this as this repo will probably be sunset in the near future.
You could contribute to the new repo: https://github.com/Azure/azure-sdk-for-js

**Pull request closed without merging**
