### PR TITLE
Table name validation for CosmosDB

### PR DESCRIPTION
**Pull request by sasahoo**
This boolean flag has been passed in table service instance, which will skip the regex validation for all table operations. The remaining validations apart from regex check are unchanged. This is a specific requirement for CosmosDB table name validation.

### CODE REVIEW

**Comment by XiaoningLiu** [comment]
There is another PR about this change https://github.com/Azure/azure-storage-node/pull/616 in the same day of this PR. Will merge when any one of the PR is ready.

I'd prefer to update only for the validation regex method instead touching other componments.

**Comment by sasahoo** [comment]
> There is another PR about this change #616 in the same day of this PR. Will merge when any one of the PR is ready.
> 
> I'd prefer to update only for the validation regex method instead touching other components.

Any change in regex validation still failing the test cases. I tried the same earlier. I created the PR and removed the same. Passing (skip regex) a flag to Table Service (CosmosDB specific) thatz the hack I could think of, takes care required validation, which  as mentioned in this PR #615. Any regex check also shouldn't fail test cases for storage services. The changes I made here, is working locally fine for CosmosDb, behaving same as java and python platform. Once you approve the merge, we can consider of putting separate regex validation for CosmosDb as well.  

I am aware of of #616. The same is just the repeat of another PR, which I had withdrawn 2 days back. If you would like to keep that regex validation, thatz also fine, given all test cases for storage service face regression.

**Comment by sasahoo** [comment]
Hi @XiaoningLiu, I made few changes, reducing much code that earlier changes with recent commit 
**7c896a5**. There is no impact on the existing design. An external flag set for the CosmosDb check validation isTableNameValid. Local tests are fine. Also all checks have been passed here too.
`tableService.setCosmosDbTable(true);`

**Comment by sasahoo** [comment]
Hi @XiaoningLiu , Below changes for latest commit 422453e
1. Reverted all changes for all components (now same as **master** branch)
2. Only change in **validate.js**
        Check for `process.env.cosmosdb` inside `tableNameIsValid()`
        `process.env.cosmosdb =  true` in client code.
3. Merged regex validation code from #616 

Please review and let me know.

**Comment by jiacfan** [comment]
@XiaoningLiu Looks good to me as well.

**Pull request closed without merging**
