### PR TITLE
Update validator to 3.35.0

### PR DESCRIPTION
**Pull request by faust64**
`validator` is known to be vulnerable (https://snyk.io/vuln/npm:validator:20150313)
According to Snyk, version 3.35.0 would be safe to use.
Travis tests are passing. Let me know if you need anything else.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@faust64__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by hasonmsft** [comment]
@marcbachmann , thanks for your contribution. We'll to more validation accordingly to see if there is any issue.

**Comment by sumitkm** [comment]
Nudge, nudge... I was going to do a PR for the same till I found this... Please merge or bump the validator version in the next release. Thanks.

**Comment by faust64** [comment]
I've seen there's been some changes merged in, conflicting with mines.
Here's an update that should refresh our branch

**Comment by faust64** [comment]
any news on these additional validation @hasonmsft ?

**Comment by hasonmsft** [comment]
@XiaoningLiu , please take a look.

**Comment by XiaoningLiu** [comment]
@hasonmsft Thanks! Did you find any issues in the validation? We can merge it in next release if no other concerns.

**Comment by XiaoningLiu** [comment]
Hey @faust64 , can you re-send the PR to dev branch? We only merge PRs into dev branch.

**Comment by faust64** [comment]
sure, re-updating my local copy, ...
not sure how to change both branches from that PR, .... Opening a new one instead: https://github.com/Azure/azure-storage-node/pull/309

**Pull request closed without merging**
