### PR TITLE
Removed utf16 character from script file

### PR DESCRIPTION
**Pull request by kunalspathak**
Removed unicode character [0x2019](http://www.fileformat.info/info/unicode/char/2019/index.htm) from script file so it gets stored as `UTF-8` instead of `UTF-16` in Javascript engine.

### CODE REVIEW

**Comment by hasonmsft** [comment]
@kunalspathak , thanks for your contribution. Your change looks good to me. Could you re-submit your PR against our dev branch according to our [contributing guideline](https://github.com/Azure/azure-storage-node/blob/dev/CONTRIBUTING.md)?

**Comment by kunalspathak** [comment]
Done.

**Comment by hasonmsft** [comment]
Azure:master from kunalspathak:utf16. Still be the master branch? :)

**Comment by kunalspathak** [comment]
My bad. Closing this one.

**Pull request closed without merging**
