### PR TITLE
Fixes the dead link in CONTRIBUTING.md

### LINKED ISSUE #134: Dead link to contributing guidelines
It is http://azure.github.io/guidelines.html in the docs but should be https://azure.github.io/guidelines/

### PR DESCRIPTION
**Pull request by abramz**
- Fixes the link to the guidelines
	- Changes updates to the current platform branding

This fixes #134

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@abramz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by hasonmsft** [comment]
Hi @abramz , thanks for your PR and efforts. We acknowledge this issue. And at the same time, we are refining our public contribution process to take public PR. Please stay tuned.

**Comment by hasonmsft** [comment]
@abramz , thank you for your contribution. We just setup the process for our repo to take community contribution. You can find the updated process from [Contributing.md](https://github.com/Azure/azure-storage-node/blob/dev/CONTRIBUTING.md). 

The issue you fixed in this PR is still there. Could you create a new PR based on the latest code and we'll merge your PR after the code review. It'll help us to test the end-to-end community contribution process. 

Thanks,
Haibo

**Comment by abramz** [comment]
Is the link still the one you guys want? It isn't dead but just want to make sure. Otherwise should be good.

**Comment by hasonmsft** [comment]
@abramz , the code change of your PR still looks good to me. Just need you to re-send the PR as our process gets changed. You need to raise PR against the dev branch instead of master branch to be compliant with our new process.

**Pull request closed without merging**
